stages:
  clean_data:
    cmd: python model/clean_data.py
    deps:
    - data/census.csv
    - model/clean_data.py
    outs:
    - data/census_cleaned.csv
  train_model:
    cmd: python model/train_model.py
    deps:
    - data/census_cleaned.csv
    - model/train_model.py
    outs:
    - model/artifacts/MinMaxScaler.joblib
    - model/artifacts/LabelBinarizer.joblib
    - model/artifacts/OneHotEncoder.joblib
    - model/artifacts/model.joblib
    - model/artifacts/test.joblib
    - model/artifacts/train.joblib