# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install 'dvc[s3]'
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: create aws configuration
        run: |
        mkdir .aws
        touch .aws/credentials
        touch .aws/config
        echo [udacity_mlops] >> .aws/credentials
        echo aws_access_key_id = ${{secrets.AWS_ACCESS_KEY_ID}} >> .aws/credentials
        echo aws_secret_access_key = ${{secrets.AWS_SECRET_KEY}} >> .aws/credentials
        echo [profile udacity_mlops] >> .aws/config
        echo region = us-east-2 >> .aws/config
    - name: Get artifacts for testing
      run: |
        dvc get-url https://github.com/kevinpmcgee14/ml_api_demo/model/artifacts/ 
    - name: start local api for testing
      run: uvicorn src.main:app --reload
    - name: Test with pytest
      run: pytest
